### PR TITLE
hierophant endpoint `/dead-contemplants`

### LINKED ISSUE #44: list of failed contemplants
Currently when a contemplant is removed it is just taken out of the list of active contemplants.  This is an issue because we need to know the address of the failed contemplant and the reason so we can debug & stop the machine the contemplant is running on.

### PR DESCRIPTION
**Pull request by JossDuff**
closes #44 

Adds a list of contemplants that the hierophant has removed at `/dead-contemplants` with their state at the time they were removed.  Big maintainability improvement

### CODE REVIEW

File: hierophant/hierophant/src/config.rs [hunk 1]
```diff
@@ -34,10 +34,6 @@ pub struct Config {
     // Make mock proofs instead of real proofs.  Witnessgen still happens.
     #[serde(default = "default_mock_mode")]
     pub mock_mode: bool,
-    // The amount of proofs to cache on-disk for persistence.
-    // Keeps most recently completed proofs.
-    #[serde(default = "default_proof_cache_size")]
-    pub proof_cache_size: usize,
```
Comment (JossDuff) [inline hierophant/hierophant/src/config.rs:40]: This was totally unused
